version: '3.8'

services:
  backend:
    build:
      context: .              # Setzt das Hauptverzeichnis als Kontext
      dockerfile: backend/Dockerfile
    container_name: cys_chatbot_backend
    ports:
      - "8000:8000"
    networks:
      - chatbot-network

  frontend:
    build:
      context: .              # Setzt das Hauptverzeichnis als Kontext
      dockerfile: frontend/Dockerfile
    container_name: cys_chatbot_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - chatbot-network
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000

networks:
  chatbot-network:
    driver: bridge
