services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: cys_chatbot_chroma
    ports:
      - "8000:8000"
    networks:
      - chatbot-network

  backend:
    build:
      context: .              # Setzt das Hauptverzeichnis als Kontext
      dockerfile: backend/Dockerfile
    container_name: cys_chatbot_backend
    ports:
      - "8080:8080"
    environment:
      CHROMA_HOST: ${CHROMA_HOST}
      CHROMA_PORT: ${CHROMA_PORT}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL_NAME: ${OPENAI_MODEL_NAME}
      OPENAI_API_TYPE: ${OPENAI_API_TYPE}
    depends_on:
      - chromadb
    networks:
      - chatbot-network

  frontend:
    build:
      context: .              # Setzt das Hauptverzeichnis als Kontext
      dockerfile: frontend/Dockerfile
    container_name: cys_chatbot_frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
    depends_on:
      - backend
    networks:
      - chatbot-network

networks:
  chatbot-network:
    name: chatbot-network
    driver: bridge