services:
  chromadb:
    image: chromadb/chroma:0.5.13
    container_name: cys_chatbot_chroma
    ports:
      - "8000:8000"
    networks:
      - chatbot-network

  backend:
    build:
      context: .              # Setzt das Hauptverzeichnis als Kontext
      dockerfile: backend/Dockerfile
    container_name: cys_chatbot_backend
    ports:
      - "8080:8080"
    environment:
      - CHROMADB_HOST=http://chromadb:8000
    depends_on:
      - chromadb
    networks:
      - chatbot-network

  frontend:
    build:
      context: .              # Setzt das Hauptverzeichnis als Kontext
      dockerfile: frontend/Dockerfile
    container_name: cys_chatbot_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - chatbot-network

networks:
  chatbot-network:
    name: chatbot-network
    driver: bridge